### ISSUE TITLE
Error : Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by cbweixin** [saintdan/spring-rest-oauth2-sample#1]
by following the steps , when I do 
```shell
./gradlew clean build bootRun
```
I got an Error like this :
```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```
in your `.gitignore` file, you ignore all the jar file, but I guess you still need to check in your `gradle/wrapper/gradle-wrapper.jar` 

thanks for providing such a good projet!

**Comment by saintdan** [comment]
@cbweixin 
Thank you for reminding me.
I have uploaded `gradle/wrapper/gradle-wrapper.jar`.
