### ISSUE TITLE
401 for /oauth/token

### ISSUE THREAD

**Issue by lishoujian** [saintdan/spring-rest-oauth2-sample#14]
when I use 
 curl -X POST -vu ios_app:123456 http://localhost:8080/oauth/token -H "Accept: application/json" -d "password=admin&username=admin&grant_type=password&scope=read&client_secret=123456&client_id=ios_app"

it replay like this:
{"timestamp":1446625431561,"status":401,"error":"Unauthorized","message":"Client ios_app does not exist!","path":"/oauth/token"}

how can I run it Correct！
thanks for your reply!

**Comment by steveGuRen** [comment]
in src//test/java/com/saintdan/framework/repo,run "Seed.java",add a client in table "clients" .because the message say "client Ios_app is not exist!",so you can check your database in table "clients".

**Comment by saintdan** [comment]
THX, @steveGuRen
