### ISSUE TITLE
你好，我读了您的项目，遇到些问题...

### ISSUE THREAD

**Issue by SuperNoobTao** [saintdan/spring-rest-oauth2-sample#39]
headers: Authorization: Basic aW9zX2FwcDoxMjM0NTY= (Encrypt client_id:client_secret by HTTP Basic)
我知道aW9zX2FwcDoxMjM0NTY 这个是用clientid和secret生成的字段，那后面的部分是什么呢？感觉并不需要，但是我把后面的部分删了之后却出现这个身份验证的弹窗..我百思不得其解，希望作者有空能帮我解答一下，非常感谢！！！
![image](https://cloud.githubusercontent.com/assets/16486344/20347343/9258fc66-ac3b-11e6-9968-babf44e20961.png)

**Comment by saintdan** [comment]
Authorization: Basic aW9zX2FwcDoxMjM0NTY=

**Comment by SuperNoobTao** [comment]
真的是诶...啊..我以为 “=” 代表左边的等于右边所导出的..没想到是生成出来就带着的..回复的好快,感谢热心的作者!!!!!!!!!!!!，你不说我估计一直都发现不了~-D

**Comment by saintdan** [comment]
不客气～
