### ISSUE TITLE
我又来了...

### ISSUE THREAD

**Issue by SuperNoobTao** [saintdan/spring-rest-oauth2-sample#40]
作者大大，我看到你的项目里的userReposity接口有
Optional<User> findByUsrAndValidFlag这个方法，但是我找不到这个方法的实现...我调试一下，发现进入了JdkDynamicAopProxy的invoke 方法里，应该是是被拦截了，然后我就云里雾里了。

其实我想问的是，Optional<User>  findByUsrAndValidFlag这个方法应该是靠Usr和ValidFlag两个字段去数据库查找的，但是我不知道为什么可以这样。难道是因为Optional<T>的原因？可是我查找了Optional<T>，发现它只是一个容器类，为了更好的配合java8的函数式编程。

至此，我的思路已经完全断了，不知道该往哪个方向走..我就是想不明白，以Optional<T> 开头的那些类比如 ：
Optional<T> findById(ID id);
Optional<Role> findByNameAndValidFlag(String name, ValidFlag validFlag);
Optional<User> findByUsrAndValidFlag(String usr, ValidFlag validFlag);
是怎么向数据库查找数据的。
希望作者大大简单的说明一下，我没有思路,,,不知道该怎么查....

**Comment by SuperNoobTao** [comment]
哦~还有一个问题，在WebSecurityConfiguration中，configure(AuthenticationManagerBuilder auth)中是security认证的自定义实现可以验证用户并得到用户权限列表，但是并没有configure(HttpSecurity http)security授权的实现，这是为什么呢？（最近在认真拜读您的代码，可能遇到问题有点多..）

**Comment by saintdan** [comment]
Optional是一个容器，它可以对内部的对象进行函数式的操作，如果你使用的是IDEA，你可以进Optional源码看到它各方法的注释和用法。
因为repository的东西，都是继承自spring data jpa的接口，所有的实现，spring帮你写好了。
findByUsrAndValidFlag，就是说只需要提供实体中的usr和validFlag参数即可，spring可按名称自动处理查询对象。
想要玩java，还得用IDEA。

**Comment by SuperNoobTao** [comment]
了解了，thank you~~最近正在认真拜读您的代码，获益良多~

**Comment by saintdan** [comment]
不客气
