### ISSUE TITLE
@AND @SPEC等注解

### ISSUE THREAD

**Issue by SuperNoobTao** [saintdan/spring-rest-oauth2-sample#46]
@And({
          @Spec(path = "usr", spec = Like.class),
          @Spec(path = "name", spec = Like.class),
          @Spec(path = "validFlag", constVal = "VALID", spec = In.class),
          @Spec(path = "createdDate", params = {"createdDateAfter", "createdDateBefore"}, spec = DateBetween.class)}) Specification<User> userSpecification,
      UserParam param
你好作者大大:
1.这是usercontroller里的一段，想问一下那些注解的意思，我查了下网上好像没有关于此类注解的东西，希望作者能具体讲一下，比如@Spec(path = "usr", spec = Like.class) path是何意，Like.class是做什么的？
2.还有就是，作者有 讲解这些注解 的网站吗？？..我点进去看源码看的一愣一愣的。。
![image](https://cloud.githubusercontent.com/assets/16486344/20958025/43e34bdc-bc8e-11e6-9c8b-e2d5d17e7fed.png)
3.我在自己的程序用这段代码的时候遇到了这个异常。。(获取用户列表的代码)
![image](https://cloud.githubusercontent.com/assets/16486344/20958083/b0f098d8-bc8e-11e6-9472-1080b134011a.png)
完全没头绪，几乎就是复制你的代码的，搞不太明白，如果作者遇到过类似的希望能给我个思路~

**Comment by saintdan** [comment]
README里就说了，用的是[specification-arg-resolver](https://github.com/tkaczmarzyk/specification-arg-resolver)
另外已经更新了，建议你pull下。

**Comment by SuperNoobTao** [comment]
啊..没看到 好的~！
