### ISSUE TITLE
{"error":"invalid_grant","error_description":"Invalid username/password"}*

### ISSUE THREAD

**Issue by soundcodehub** [saintdan/spring-rest-oauth2-sample#47]
When trying to get the token, getting using following command

curl -X POST -vu ios_app:123456 http://localhost:8080/oauth/token -H "Accept: application/json" -d "password=admin&username=admin&grant_type=password&scope=read&client_secret=123456&client_id=ios_app"

Getting 

{"error":"invalid_grant","error_description":"Invalid username/password"}*

**Comment by saintdan** [comment]
Hi there,

Have you imported the init.sql which in src/main/resources folder.
By the way, you can just use command like this:

curl -X POST -vu ios_app:123456 http://localhost:8080/oauth/token -H "Accept: application/json" -d "password=admin&username=admin&grant_type=password&scope=read"
